# Generated by Django 5.2.1 on 2025-08-21 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cardiolog',
            name='calorie_tra_user_id_9c2bfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='foodlog',
            name='calorie_tra_user_id_e3acb2_idx',
        ),
        migrations.RenameField(
            model_name='cardiolog',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='foodlog',
            old_name='time_stamp',
            new_name='timestamp',
        ),
        migrations.AddIndex(
            model_name='cardiolog',
            index=models.Index(fields=['user', 'timestamp'], name='calorie_tra_user_id_75c247_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlog',
            index=models.Index(fields=['user', 'timestamp'], name='calorie_tra_user_id_6c3a8a_idx'),
        ),
    ]
