# Generated by Django 5.2.1 on 2025-08-21 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0002_remove_cardiolog_calorie_tra_user_id_9c2bfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiolog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
