# Generated by Django 5.2.1 on 2025-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cardio_goal',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
