# Generated by Django 5.2.1 on 2025-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0005_userprofile_cardio_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cardio_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
