# Generated by Django 5.2.1 on 2025-09-23 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0006_alter_userprofile_cardio_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
